#!/usr/bin/env bash
# MySystem setup — idempotent bootstrap for ~/.claude
# Usage: cd ~/.claude && ./setup.sh
#
# What this does:
#   1. Clone or update full external skill repos (gstack)
#   2. Run gstack's own setup (symlinks 20+ skills into ~/.claude/skills/)
#   3. Sparse cherry-pick individual skills from other repos (cache + symlink)
#   4. Register external skill dirs in .git/info/exclude so the tracked
#      .gitignore stays small.
#   5. Validate skill symlinks
#   6. Verify RTK presence (voyagerx internal token-compression proxy)

set -euo pipefail

cd "$(dirname "$0")"
REPO_ROOT="$(pwd)"

echo "=== MySystem Setup ==="
echo ""

# ── Full external skill repositories ─────────────────────────
# Format: "name|url|branch"
# These repos run their own setup script that installs many skills.
EXTERNAL_REPOS=(
  "gstack|https://github.com/garrytan/gstack.git|main"
)

# ── Sparse cherry-pick skills ────────────────────────────────
# Format: "skill-name|url|branch|subpath-in-repo"
# Clones the repo into external-skills/<skill-name>/ (cache, not tracked)
# and symlinks <subpath> as skills/<skill-name>/.
SPARSE_SKILLS=(
  "requesting-code-review|https://github.com/obra/superpowers.git|main|skills/requesting-code-review"
  "deep-research|https://github.com/affaan-m/everything-claude-code.git|main|.agents/skills/deep-research"
)

clone_or_pull() {
  local dest="$1" url="$2" branch="$3"

  if [ -d "$dest/.git" ]; then
    echo "  pulling $dest..."
    if ! ( cd "$dest" && git pull --ff-only origin "$branch" 2>&1 | sed 's/^/    /' ); then
      echo "  ✗ $dest: pull failed (uncommitted changes?)."
      echo "    Fix manually: cd $dest && git stash || git reset --hard origin/$branch"
      exit 1
    fi
  else
    echo "  cloning $dest from $url..."
    [ -e "$dest" ] && rm -rf "$dest"
    git clone --branch "$branch" "$url" "$dest" 2>&1 | sed 's/^/    /'
  fi
}

# ── [1/5] Full external repos ────────────────────────────────
echo "[1/5] Syncing full external skill repos..."
for entry in "${EXTERNAL_REPOS[@]}"; do
  IFS='|' read -r name url branch <<< "$entry"
  clone_or_pull "skills/$name" "$url" "$branch"
done
echo "  ✓ external repos ready"

# ── [2/5] Run gstack's own setup ─────────────────────────────
echo ""
echo "[2/5] Running gstack setup..."
if [ -x "skills/gstack/setup" ]; then
  ( cd skills/gstack && ./setup 2>&1 | sed 's/^/  /' )
  echo "  ✓ gstack skills installed"
else
  echo "  ✗ skills/gstack/setup not found or not executable"
  exit 1
fi

# ── [3/5] Sparse cherry-pick skills ──────────────────────────
echo ""
echo "[3/5] Installing sparse cherry-pick skills..."
mkdir -p external-skills
for entry in "${SPARSE_SKILLS[@]}"; do
  IFS='|' read -r skill_name url branch subpath <<< "$entry"
  cache_dir="external-skills/$skill_name"
  link_target="skills/$skill_name"
  abs_source="$REPO_ROOT/$cache_dir/$subpath"

  clone_or_pull "$cache_dir" "$url" "$branch"

  if [ ! -e "$abs_source" ]; then
    echo "  ✗ $skill_name: subpath '$subpath' not found in repo"
    exit 1
  fi

  # Replace any existing target (file, dir, or stale symlink)
  if [ -e "$link_target" ] || [ -L "$link_target" ]; then
    rm -rf "$link_target"
  fi
  ln -s "$abs_source" "$link_target"
  echo "  ✓ $skill_name → $cache_dir/$subpath"
done

# Register external dirs in local-only ignore so they don't pollute git status
EXCLUDE_FILE=".git/info/exclude"
{
  echo "# Auto-generated by setup.sh — external skill dirs"
  echo "external-skills/"
  for entry in "${EXTERNAL_REPOS[@]}"; do
    IFS='|' read -r name _ _ <<< "$entry"
    echo "skills/$name/"
  done
  # Also exclude any gstack-installed skill dir that isn't whitelisted in .gitignore.
  # gstack symlinks land directly under skills/. We register each non-whitelisted
  # skill dir found post-install so `git status` stays clean.
  for d in skills/*/; do
    name=$(basename "$d")
    case "$name" in
      verify-test) continue ;;  # tracked user-owned skill
      gstack) continue ;;       # already listed above
    esac
    echo "skills/$name/"
  done
} > "$EXCLUDE_FILE"

# ── [4/5] Validate ───────────────────────────────────────────
echo ""
echo "[4/5] Validating..."
BROKEN=0
TOTAL=0
for skill_dir in skills/*/; do
  skill_name=$(basename "$skill_dir")
  [ "$skill_name" = "gstack" ] && continue
  skill_file="$skill_dir/SKILL.md"

  if [ -L "$skill_dir" ] || [ -L "$skill_file" ]; then
    TOTAL=$((TOTAL + 1))
    if [ ! -e "$skill_file" ]; then
      echo "  ✗ $skill_name — broken symlink"
      BROKEN=$((BROKEN + 1))
    fi
  elif [ -f "$skill_file" ]; then
    TOTAL=$((TOTAL + 1))
  fi
done

if [ "$BROKEN" -eq 0 ]; then
  echo "  ✓ $TOTAL skills OK"
else
  echo "  ✗ $BROKEN/$TOTAL skills broken — try re-running ./setup.sh"
  exit 1
fi

# ── [5/5] RTK ────────────────────────────────────────────────
if command -v rtk >/dev/null 2>&1; then
  echo "  ✓ rtk present ($(rtk --version 2>/dev/null | head -1 || echo unknown))"
else
  echo "  ⚠ rtk not on PATH — see RTK.md for install (token compression hook will no-op)"
fi

echo ""
echo "=== Setup Complete ==="
echo "  Version: $(cat VERSION 2>/dev/null || echo "?")"
echo "  Skills:  $TOTAL"
echo "  Hooks:   $(ls hooks/*.sh 2>/dev/null | wc -l | tr -d ' ')"
echo ""
echo "Start a new Claude Code session to pick up changes."
